// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL-4JjCpjHXpgZS6EZ-qLp3c4eEyWJOfU',
    appId: '1:163641562400:web:e1cab5d9fe40b310f17345',
    messagingSenderId: '163641562400',
    projectId: 'teste-1e6d5',
    authDomain: 'teste-1e6d5.firebaseapp.com',
    storageBucket: 'teste-1e6d5.appspot.com',
    measurementId: 'G-C3V80ZDERV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArTdDo1N2v9ZIIAeaf-q3HslQoQVZPiV8',
    appId: '1:163641562400:android:8c89f184c61d48f8f17345',
    messagingSenderId: '163641562400',
    projectId: 'teste-1e6d5',
    storageBucket: 'teste-1e6d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsZF30jMiurjy8Hz9VjXYGRuTUJp7hTjI',
    appId: '1:163641562400:ios:3826d2bb1f3e0f74f17345',
    messagingSenderId: '163641562400',
    projectId: 'teste-1e6d5',
    storageBucket: 'teste-1e6d5.appspot.com',
    iosClientId: '163641562400-7naib1c5p9shdqnpecmmrnb5pt8b73eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.appviagem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsZF30jMiurjy8Hz9VjXYGRuTUJp7hTjI',
    appId: '1:163641562400:ios:4aaedd7cac80c155f17345',
    messagingSenderId: '163641562400',
    projectId: 'teste-1e6d5',
    storageBucket: 'teste-1e6d5.appspot.com',
    iosClientId: '163641562400-tqr2skpbrfbegfaoo72dqs3489enfd7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.appviagem.RunnerTests',
  );
}
